'use strict';
const $=(selector,root=document)=>root.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const cfg=window.RIDNE_CONFIG;
const client=window.supabase?.createClient(cfg.url,cfg.key,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function formatDate(value){return value?new Intl.DateTimeFormat('uk-UA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';}
async function api(action,data={}){if(!client)throw Error('Сервіс входу не завантажився.');const {data:{session}}=await client.auth.getSession();if(!session)throw Error('Увійдіть як власник RIDNE.');const response=await fetch(`${cfg.url}/functions/v1/ridne-web`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.key,Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...data})});const json=await response.json();if(!response.ok)throw Error(json.error||'Не вдалося виконати дію.');return json;}
function meta(items){return `<dl class="moderation-meta">${items.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'—')}</dd></div>`).join('')}</dl>`;}
function actions(type,id){return `<div class="moderation-actions"><button class="btn primary" data-decision="approve" data-type="${type}" data-id="${esc(id)}">Схвалити</button><button class="btn tertiary reject-action" data-decision="reject" data-type="${type}" data-id="${esc(id)}">На уточнення</button></div>`;}
function render(data){
  $('#seller-count').textContent=data.sellers.length;$('#product-count').textContent=data.products.length;
  $('#seller-queue').innerHTML=data.sellers.length?data.sellers.map(s=>`<article class="moderation-card"><div><span class="account-kicker">Профіль · ${esc(formatDate(s.submitted_at||s.created_at))}</span><h3>${esc(s.display_name)}</h3><p>${esc(s.email||'Без email')}</p></div>${meta([['Тип',s.producer_type],['Локація',[s.locality,s.oblast].filter(Boolean).join(', ')]])}${actions('seller',s.id)}</article>`).join(''):'<div class="queue-empty">Нових профілів немає.</div>';
  $('#product-queue').innerHTML=data.products.length?data.products.map(p=>{const seller=Array.isArray(p.seller_profiles)?p.seller_profiles[0]:p.seller_profiles;const category=Array.isArray(p.categories)?p.categories[0]:p.categories;return `<article class="moderation-card">${p.image_url?`<img class="moderation-photo" src="${esc(p.image_url)}" alt="${esc(p.title)}">`:''}<div><span class="account-kicker">Товар · ${esc(formatDate(p.submitted_at||p.created_at))}</span><h3>${esc(p.title)}</h3><p>${esc(p.description||'Без опису')}</p></div>${meta([['Ціна',`${Number(p.price_uah).toLocaleString('uk-UA')} ₴ / ${p.unit}`],['Кількість',p.available_quantity],['Категорія',category?.name_uk],['Виробник',`${seller?.display_name||'—'} · ${seller?.verification_status||'—'}`],['Походження',[p.origin_locality,p.origin_oblast].filter(Boolean).join(', ')],['Зберігання',p.storage_requirements]])}${actions('product',p.id)}</article>`;}).join(''):'<div class="queue-empty">Нових товарів немає.</div>';
}
async function load(){try{$('#admin-status').textContent='Завантажуємо заявки…';const data=await api('admin-dashboard');render(data);$('#admin-status').textContent=data.sellers.length||data.products.length?'Спочатку перевірте виробника, потім його товар.':'Черга чиста.';}catch(error){$('#admin-status').innerHTML=`${esc(error.message)} <a href="/account/">Перейти до входу</a>`;}}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-decision]');if(!button)return;let reason='';if(button.dataset.decision==='reject'){reason=prompt('Що потрібно уточнити?','Потрібні уточнення')||'';if(!reason)return;}const card=button.closest('.moderation-card');card.setAttribute('aria-busy','true');try{await api(button.dataset.type==='seller'?'moderate-seller':'moderate-product',{[button.dataset.type==='seller'?'seller_id':'product_id']:button.dataset.id,decision:button.dataset.decision,reason});toast(button.dataset.decision==='approve'?'Схвалено.':'Повернуто на уточнення.');await load();}catch(error){toast(error.message);card.removeAttribute('aria-busy');}});
$('#sync-telegram').addEventListener('click',async()=>{const button=$('#sync-telegram');button.disabled=true;try{const result=await api('sync-moderation');toast(result.processed?`Передано заявок: ${result.processed}`:'Черга вже синхронізована.');}catch(error){toast(error.message);}finally{button.disabled=false;}});
load();
