'use strict';
const $=(selector,root=document)=>root.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const cfg=window.RIDNE_CONFIG;
const client=window.supabase?.createClient(cfg.url,cfg.key,{auth:{flowType:'pkce',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const ADMIN_EMAIL='doctorgebel@gmail.com';
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function formatDate(value){return value?new Intl.DateTimeFormat('uk-UA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';}
async function api(action,data={}){if(!client)throw Error('Сервіс входу не завантажився.');const {data:{session}}=await client.auth.getSession();if(!session)throw Error('Увійдіть як власник RIDNE.');const response=await fetch(`${cfg.url}/functions/v1/ridne-web`,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.key,Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...data})});const json=await response.json();if(!response.ok)throw Error(json.error||'Не вдалося виконати дію.');return json;}
function meta(items){return `<dl class="moderation-meta">${items.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'—')}</dd></div>`).join('')}</dl>`;}
function actions(type,id){return `<div class="moderation-actions"><button class="btn primary" data-decision="approve" data-type="${type}" data-id="${esc(id)}">Схвалити</button><button class="btn tertiary reject-action" data-decision="reject" data-type="${type}" data-id="${esc(id)}">На уточнення</button></div>`;}
function render(data){
  $('#seller-count').textContent=data.sellers.length;$('#product-count').textContent=data.products.length;
  $('#seller-queue').innerHTML=data.sellers.length?data.sellers.map(s=>`<article class="moderation-card"><div><span class="account-kicker">Профіль · ${esc(formatDate(s.submitted_at||s.created_at))}</span><h3>${esc(s.display_name)}</h3><p>${esc(s.email||'Без email')}</p></div>${meta([['Тип',s.producer_type],['Локація',[s.locality,s.oblast].filter(Boolean).join(', ')]])}${actions('seller',s.id)}</article>`).join(''):'<div class="queue-empty">Нових профілів немає.</div>';
  $('#product-queue').innerHTML=data.products.length?data.products.map(p=>{const seller=Array.isArray(p.seller_profiles)?p.seller_profiles[0]:p.seller_profiles;const category=Array.isArray(p.categories)?p.categories[0]:p.categories;return `<article class="moderation-card">${p.image_url?`<img class="moderation-photo" src="${esc(p.image_url)}" alt="${esc(p.title)}">`:''}<div><span class="account-kicker">Товар · ${esc(formatDate(p.submitted_at||p.created_at))}</span><h3>${esc(p.title)}</h3><p>${esc(p.description||'Без опису')}</p></div>${meta([['Ціна',`${Number(p.price_uah).toLocaleString('uk-UA')} ₴ / ${p.unit}`],['Кількість',p.available_quantity],['Категорія',category?.name_uk],['Виробник',`${seller?.display_name||'—'} · ${seller?.verification_status||'—'}`],['Походження',[p.origin_locality,p.origin_oblast].filter(Boolean).join(', ')],['Зберігання',p.storage_requirements]])}${actions('product',p.id)}</article>`;}).join(''):'<div class="queue-empty">Нових товарів немає.</div>';
}
function showLogin(message=''){$('#admin-login').hidden=false;$('#admin-app').hidden=true;$('#admin-logout').hidden=true;$('#admin-login-status').textContent=message;}
function showAdmin(){$('#admin-login').hidden=true;$('#admin-app').hidden=false;$('#admin-logout').hidden=false;}
async function sendAdminLink(){if(!client)throw Error('Сервіс входу не завантажився.');const {error}=await client.auth.signInWithOtp({email:ADMIN_EMAIL,options:{emailRedirectTo:'https://ridne.store/admin/moderation/',shouldCreateUser:false}});if(error){if(error.status===429||/rate/i.test(error.message||''))throw Error('Посилання вже запитано. Зачекайте 60 секунд.');throw Error('Не вдалося надіслати посилання. Спробуйте ще раз.');}}
async function load(){try{$('#admin-status').textContent='Завантажуємо заявки…';const data=await api('admin-dashboard');render(data);$('#admin-status').textContent=data.sellers.length||data.products.length?'Спочатку перевірте виробника, потім його товар.':'Черга чиста.';}catch(error){$('#admin-status').textContent=error.message;}}
async function start(){if(!client){showLogin('Сервіс входу не завантажився. Оновіть сторінку.');return;}const {data:{session}}=await client.auth.getSession();if(!session){showLogin(new URLSearchParams(location.search).has('error')?'Посилання недійсне або вже використане. Запросіть нове.':'');return;}if(session.user.email?.toLowerCase()!==ADMIN_EMAIL){await client.auth.signOut();showLogin('Цей розділ доступний лише власнику RIDNE.');return;}showAdmin();await load();}
$('#admin-login-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#admin-login-form button');button.disabled=true;try{await sendAdminLink();$('#admin-login-status').textContent='Посилання надіслано на doctorgebel@gmail.com. Відкрийте його в цьому браузері — ви одразу потрапите в Administration.';setTimeout(()=>button.disabled=false,60000);}catch(error){$('#admin-login-status').textContent=error.message;button.disabled=false;}});
$('#admin-logout').addEventListener('click',async()=>{await client.auth.signOut();showLogin('Ви вийшли з Administration.');});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-decision]');if(!button)return;let reason='';if(button.dataset.decision==='reject'){reason=prompt('Що потрібно уточнити?','Потрібні уточнення')||'';if(!reason)return;}const card=button.closest('.moderation-card');card.setAttribute('aria-busy','true');try{await api(button.dataset.type==='seller'?'moderate-seller':'moderate-product',{[button.dataset.type==='seller'?'seller_id':'product_id']:button.dataset.id,decision:button.dataset.decision,reason});toast(button.dataset.decision==='approve'?'Схвалено.':'Повернуто на уточнення.');await load();}catch(error){toast(error.message);card.removeAttribute('aria-busy');}});
$('#sync-telegram').addEventListener('click',async()=>{const button=$('#sync-telegram');button.disabled=true;try{const result=await api('sync-moderation');toast(result.processed?`Передано заявок: ${result.processed}`:'Черга вже синхронізована.');}catch(error){toast(error.message);}finally{button.disabled=false;}});
start();
